# Generated by Django 4.1.7 on 2023-04-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Guide_Lines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineer',
            new_name='SoftwareEngineer',
        ),
    ]
